package xyz.ubatv.kingdoms.rankSystem;

public enum Permissions {
    TESTER,
    INVSEE,
    KIT_VIP,
    KIT_MVP,
    GAMEMODE,
    TELEPORT,
    PLACE_LUNCHBOX,
    SET_LOCATION,
    RANK_MANAGEMENT,
    CLEAR_INVENTORY_OTHERS,
    CLEAR_INVENTORY,
    CLEAR_CHAT,
    PRIVATE_CHEST,
    ENDERCHEST,
    ENDERCHEST_OTHERS,
    ECON_MANAGEMENT,
    MUTE,
    HOLOGRAMS,
    SHOP_NPC
}
